### ISSUE TITLE
Live Stream v1

### ISSUE THREAD

**Issue by lnikj** [sensel/C74-Max-Examples#1]
Max beginner here, so bear that in mind, but I had some issues with your initial BEAP patch that you might be able to address in the patch itself, or in documentation.

1. Both Mono outputs are set to Channel 1, leaving L channel sound only.
2. The contours do not save in the Spectral Filter - might be worth leaving a note in the patch that people need to draw them or only the thinnest sound will be passed through.
3. The patch cannot handle anything more than the slowest key changes on any buffer setting without clicking.

**Comment by nyboer** [comment]
Thanks for the feedback. I just added a preset manager so it loads a preset to fix issues 1 and 2, and make it easier to create your own contours and save them to a preset. For issue 3, I only get a few clicks when I rapidly hammer on the keys, but your results may vary. BEAP is not the most efficient way to create patches in Max, but it is a great way to learn.
