### ISSUE TITLE
"L*" subpatcher in Multitouch from MPE example not working in Windows

### ISSUE THREAD

**Issue by dundass** [sensel/C74-Max-Examples#2]
Hey, just tried to load up the "Multitouch from MPE" example on Windows but seeing as the "*" symbol isn't allowed in filenames on Windows (I know..), the L* subpatchers don't initialise. Not a huge thing since the filenames/refs can be manually changed but might save some folks some hassle. Thanks

**Comment by nyboer** [comment]
ah...thanks for the heads up. I didn't want to call it Lmult, as that is a name of an external by Peter Elsea. I'll fix this in a bit. Guess I'll have to go the many character'd route and call it ListMult or something.

**Comment by nyboer** [comment]
fixed
