### ISSUE TITLE
Spectral Shiatsu: No Morph detected, Error 126 loading external sensel

### ISSUE THREAD

**Issue by vacuumn** [sensel/C74-Max-Examples#3]
Ableton 11
Max 8.1.10
Windows 10

No matter if I disable\enable Sensel as MIDI device, I could not make it detected by M4L device or inside Max itself. 

What could be wrong here?

**Comment by nyboer** [comment]
The error 126 was in the Max window?
You probably need to open Max and install the "sensel" package from the package manager.

**Comment by vacuumn** [comment]
> The error 126 was in the Max window?
> You probably need to open Max and install the "sensel" package from the package manager.

yes, that fixes an issue
Thanks!
